Importing numpy python library

In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,4]
arr1 = np.array(list1)
print(arr1)

[1 2 3 4]


In [3]:
arr2 = np.array([1,2,3,4])
print(arr2)

[1 2 3 4]


Creating a 2D numpy array

In [8]:
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]


Creating a 3-D numpy array

In [9]:
#creating a 3D array with 2 "slices", each of 3 rows and 4 columns
arr4 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[4,3,2,1],[8,7,6,5],[12,11,10,9]]])
print(arr4)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 4  3  2  1]
  [ 8  7  6  5]
  [12 11 10  9]]]


Check the datatype of an array

In [10]:
arr5 = np.array([1,2,3])
print(arr5.dtype)

int64


In [11]:
arr6 = np.array([1.5,2.5,3.5])
print(arr6.dtype)

float64


Check the dimension

In [16]:
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)
print(arr5.ndim)
print(arr6.ndim)

1
2
3
1
1


Check the size

In [17]:
print(arr2.size)
print(arr3.size)
print(arr4.size)
print(arr5.size)
print(arr6.size)

4
8
24
3
3


Numpy array shape attribute

In [21]:
arr7 = np.array([[1,2,3],[4,5,6]])
#returns the tuple of integers that gives size of an array in each dimension
print(arr7.shape)
print(arr3.shape)
print(arr4.shape)
print(arr2.shape)

(2, 3)
(2, 4)
(2, 3, 4)
(4,)


Numpy array itemsize attribute

In [24]:
arr8 = np.array([6,7,8,9,10])
arr9 = np.array([6,7,8,9,10], dtype=np.int32)
print(arr8.itemsize)
print(arr9.itemsize)

8
4


Numpy array data attribute

In [25]:
array1 = np.array([6,7,8])
array2 = np.array([[1,2,3],[4,5,6]])
#print memory address' of array1 and array2's data
print("\nData of array1 is: ",array1.data)
print("\nData of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x782a85f65d80>

Data of array2 is:  <memory at 0x782a863ecee0>


Access array elements using Index

In [27]:
array1 = np.array([1,2,3,4,5])
print(array1[-1])
print(array1[2])
print(array1[4])

5
3
5


Modify array elements using Index

In [29]:
array1[1] = 10
print(array1)

[ 1 10  3  4  5]
