Importing numpy python library

In [25]:
import numpy as np

In [26]:
list1 = [1,2,3,4]
arr1 = np.array(list1)
print(arr1)

[1 2 3 4]


In [27]:
arr2 = np.array([1,2,3,4])
print(arr2)

[1 2 3 4]


Creating a 2D numpy array

In [28]:
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]


Creating a 3-D numpy array

In [29]:
#creating a 3D array with 2 "slices", each of 3 rows and 4 columns
arr4 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[4,3,2,1],[8,7,6,5],[12,11,10,9]]])
print(arr4)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 4  3  2  1]
  [ 8  7  6  5]
  [12 11 10  9]]]


Check the datatype of an array

In [30]:
arr5 = np.array([1,2,3])
print(arr5.dtype)

int64


In [31]:
arr6 = np.array([1.5,2.5,3.5])
print(arr6.dtype)

float64


Check the dimension

In [32]:
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)
print(arr5.ndim)
print(arr6.ndim)

1
2
3
1
1


Check the size

In [33]:
print(arr2.size)
print(arr3.size)
print(arr4.size)
print(arr5.size)
print(arr6.size)

4
8
24
3
3


Numpy array shape attribute

In [34]:
arr7 = np.array([[1,2,3],[4,5,6]])
#returns the tuple of integers that gives size of an array in each dimension
print(arr7.shape)
print(arr3.shape)
print(arr4.shape)
print(arr2.shape)

(2, 3)
(2, 4)
(2, 3, 4)
(4,)


Numpy array itemsize attribute

In [35]:
arr8 = np.array([6,7,8,9,10])
arr9 = np.array([6,7,8,9,10], dtype=np.int32)
print(arr8.itemsize)
print(arr9.itemsize)

8
4


Numpy array data attribute

In [36]:
array1 = np.array([6,7,8])
array2 = np.array([[1,2,3],[4,5,6]])
#print memory address' of array1 and array2's data
print("\nData of array1 is: ",array1.data)
print("\nData of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x7d1fb14799c0>

Data of array2 is:  <memory at 0x7d1fa0bd1cb0>


Access array elements using Index

In [37]:
array1 = np.array([1,2,3,4,5])
print(array1[-1])
print(array1[2])
print(array1[4])

5
3
5


Modify array elements using Index

In [38]:
array1[1] = 10
print(array1)

[ 1 10  3  4  5]


Numpy statistical functions

In [39]:
marks = np.array([79,76,88,90,95])
mean_marks = np.mean(marks)
print(mean_marks)

85.6


In [40]:
marks = np.array([79,76,88,90,95])
median = np.median(marks)
print(median)

88.0


In [41]:
marks = np.array([79,76,88,90,95])
std = np.std(marks)
print(std)

7.059745037889116


In [42]:
marks = np.array([79,76,88,90,95])
std_marks = np.percentile(marks,80)
print(std_marks)

91.0


In [43]:
marks = np.array([79,76,88,90,95])
std_marks = np.min(marks)
print(std_marks)

76


In [44]:
marks = np.array([79,76,88,90,95])
std_marks = np.max(marks)
print(std_marks)

95


In [45]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.nbytes)

48


In [46]:
arr1 = np.array([1,2,3])
print(arr1.nbytes)

24


In [47]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.nbytes)

72
